version: "3.7.9"

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
